services:
  kamailio:
    image: ghcr.io/kamailio/kamailio:6.0.1-bookworm
    container_name: thundervox-kamailio
    network_mode: host
    volumes:
      - ./configuration/kamailio.cfg:/etc/kamailio/kamailio.cfg
    environment:
      - DBENGINE=NONE
      - TZ=Asia/Omsk
    restart: always

  rtpengine:
    image: fonoster/rtpengine
    container_name: thundervox-rtpengine
    network_mode: host
    restart: always
    environment:
      RTPENGINE_PUBLIC_IP: "188.225.72.135"
      RTPENGINE_BIND_NG_PORT: "4444"
      RTPENGINE_PORT_MIN: "20000"
      RTPENGINE_PORT_MAX: "30000"
      RTPENGINE_LOG_LEVEL: "7"