services:
  kamailio:
    image: ghcr.io/kamailio/kamailio:6.0.1-bookworm
    container_name: thundervox-kamailio
    network_mode: host
    volumes:
      - ./configuration/kamailio.cfg:/etc/kamailio/kamailio.cfg
      - ./log/kamailio:/var/log/kamailio
    environment:
      - DBENGINE=NONE
      - TZ=Asia/Omsk
    restart: always

  rtpproxy:
    image: sippylabs/rtpproxy
    container_name: thundervox-rtpproxy
    network_mode: host
    command: [ "-l", "188.225.72.135", "-s", "udp:127.0.0.1:22222", "-m", "20000", "-M", "30000" ]
    restart: always
